# Reference to configure the replica-set:
# https://blog.skbali.com/2019/05/mongodb-replica-set-using-docker-compose/

version: '3.1'
services: 
    mongodb_node_01:
        image: mongo
        hostname: mongodb_node_01
        container_name: mongodb_node_01
        ports: 
            - 27018:27018
        networks: 
            - mongo_cluster_network
        volumes:
            - ./data1/db:/data/db
            - ./data1/configdb:/data/configdb
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs", "--port", "27018" ]

    mongodb_node_02:
        image: mongo
        hostname: mongodb_node_02
        container_name: mongodb_node_02
        ports: 
            - 27019:27019
        networks: 
            - mongo_cluster_network
        volumes:
            - ./data2/db:/data/db
            - ./data2/configdb:/data/configdb
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs", "--port", "27019" ]

    mongodb_node_03:
        image: mongo
        hostname: mongodb_node_03
        container_name: mongodb_node_03
        ports: 
            - 27020:27020
        networks: 
            - mongo_cluster_network
        volumes:
            - ./data3/db:/data/db
            - ./data3/configdb:/data/configdb
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs", "--port", "27020" ]
    
    mongoclient:
        image: mongoclient/mongoclient
        ports: 
            - 3000:3000
        networks: 
            - mongo_cluster_network
            
networks: 
    mongo_cluster_network:
